apiVersion: v1
kind: PersistentVolume
metadata:
        name: pv1

spec:
        capacity:
                storage: 2Gi
        volumeMode: Filesystem
        accessModes:
                - ReadWriteOnce
        persistentVolumeReclaimPolicy: Recycle
        storageClassName: slow
        mountOptions:
                - hard
                - nfsvers=4.1
        nfs:
                path: /data
                server: 172.31.42.83
        claimRef:
                namespace: grras
                name: myclaim