apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: zeetron_replica
  namespace: zeetron

spec:
  # modify replicas according to your case
  replicas: 5
  selector:
    matchLabels:
            disk: ssd
  template:
    metadata:
            name: zeepod      
            labels:
              disk: ssd
    spec:
      containers:
      - name: redis
        image: redis