apiVersion: v1
kind: Service
metadata:
  labels:
    app: flipkartweb
  name: flipservice
  namespace: flipkart
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: flipkartweb
  type: ClusterIP